# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f63ed3726af30e000200b4de7d4c17e91bb496fcdaf9b9db2097bdcd898589d1e3256c836842a56150f4a636ebccd2a07d8802a9c66e8ffeeb1590feb7e06ff

test:
  secret_key_base: 80993ade26fa42e76a27b3f936f72ce36033b0aad5d6595ab522e63960686b71152bbd305f95f97dea15633eeda1aba335fa56a5265061bcd42fd2e23353e8fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
